DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	UID SERIAL PRIMARY KEY,
	NAME VARCHAR(50),
	EDAD INT CHECK(EDAD > 0)
);

INSERT INTO USERS (NAME, EDAD)
VALUES 
('NAME1', 1),
('NAME2', 2),
('NAME3', 3);

SELECT * FROM USERS;